#!/usr/bin/env swift
// Validates dicts/aime_tech_2026/*.tsv and builds the `aime_tech` text table.
//
//   swift scripts/build-dicts.swift --check            # validate only
//   swift scripts/build-dicts.swift --out <file.txt>   # validate + write table
//
// Source format (TSV): text <TAB> code <TAB> category <TAB> weight
//   code: space-separated pinyin syllables (Chinese) or lowercase [a-z0-9] (Latin)
import Foundation

let root = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent()
let sourceDir = root.appendingPathComponent("dicts/aime_tech_2026")
let categories: Set = ["ai_company", "ai_product", "ai_term", "dev_tool", "internet_slang", "brand", "platform"]

// Every legal Mandarin syllable (ü written as v).
let initials = ["", "b", "p", "m", "f", "d", "t", "n", "l", "g", "k", "h", "j", "q", "x", "zh", "ch", "sh", "r", "z", "c", "s", "y", "w"]
let syllables: Set<String> = {
    let finals = ["a", "o", "e", "ai", "ei", "ao", "ou", "an", "en", "ang", "eng", "ong", "er", "i", "ia", "ie", "iao", "iu", "ian", "in",
                  "iang", "ing", "iong", "u", "ua", "uo", "uai", "ui", "uan", "un", "uang", "ueng", "v", "ve", "ue", "van", "vn", "m", "n", "ng", "hm", "hng"]
    var set = Set<String>()
    for i in initials { for f in finals { set.insert(i + f) } }
    return set
}()

var errors: [String] = []
var rows: [(text: String, code: String, weight: Int)] = []
var seen = Set<String>()

let files = ((try? FileManager.default.contentsOfDirectory(atPath: sourceDir.path)) ?? []).filter { $0.hasSuffix(".tsv") }.sorted()
if files.isEmpty { errors.append("no .tsv files in \(sourceDir.path)") }
for file in files {
    let text = (try? String(contentsOf: sourceDir.appendingPathComponent(file), encoding: .utf8)) ?? ""
    for (number, rawLine) in text.split(separator: "\n", omittingEmptySubsequences: false).enumerated() {
        let line = rawLine.trimmingCharacters(in: .whitespaces)
        if line.isEmpty || line.hasPrefix("#") { continue }
        let where_ = "\(file):\(number + 1)"
        let cols = line.components(separatedBy: "\t")
        guard cols.count == 4 else { errors.append("\(where_): expected 4 columns, got \(cols.count)"); continue }
        let (word, code, category) = (cols[0], cols[1], cols[2])
        guard let weight = Int(cols[3]), (1...100).contains(weight) else { errors.append("\(where_): weight must be 1-100"); continue }
        guard categories.contains(category) else { errors.append("\(where_): unknown category \(category)"); continue }
        guard !word.isEmpty else { errors.append("\(where_): empty text"); continue }
        let parts = code.split(separator: " ").map(String.init)
        if parts.count > 1 {
            if let bad = parts.first(where: { !syllables.contains($0) && !$0.allSatisfy({ $0.isASCII && ($0.isLetter || $0.isNumber) }) }) {
                errors.append("\(where_): invalid pinyin syllable '\(bad)' in \(word)")
                continue
            }
        } else if !code.allSatisfy({ $0.isASCII && ($0.isLowercase || $0.isNumber) }) {
            errors.append("\(where_): code must be lowercase letters/digits: '\(code)'")
            continue
        }
        let joined = parts.joined()
        let key = "\(word)\t\(joined)"
        if seen.contains(key) { continue } // duplicates across batches are harmless; keep the first
        seen.insert(key)
        rows.append((word, joined, weight))
    }
}

if !errors.isEmpty {
    errors.prefix(50).forEach { FileHandle.standardError.write(Data("error: \($0)\n".utf8)) }
    FileHandle.standardError.write(Data("\(errors.count) error(s)\n".utf8))
    exit(1)
}

let args = CommandLine.arguments
if let index = args.firstIndex(of: "--out"), index + 1 < args.count {
    rows.sort { ($0.code, -$0.weight) < ($1.code, -$1.weight) }
    var out = """
    # Rime table
    # coding: utf-8
    #@/db_name\taime_tech.txt
    #@/db_type\ttabledb
    #
    # AIME · 2026 AI / internet vocabulary (CC BY 4.0)
    # Generated by scripts/build-dicts.swift from dicts/aime_tech_2026 — do not edit.
    #
    # 此行之后不能写注释

    """
    for row in rows { out += "\(row.text)\t\(row.code)\t\(row.weight)\n" }
    try out.write(to: URL(fileURLWithPath: args[index + 1]), atomically: true, encoding: .utf8)
    print("aime_tech: \(rows.count) entries → \(args[index + 1])")
} else {
    print("aime_tech: \(rows.count) entries OK")
}
